# This script process *.contigs_plasmid_summary.tsv and *.contigs_virus_summary.tsv files generated by geNomad

import os
import pandas as pd

# Define the path to the geNomad folder
base_path = "result_BlendARGs/VirusIdentification/geNomad"

# Initialize empty DataFrames for plasmid and virus summaries
plasmid_data = pd.DataFrame()
virus_data = pd.DataFrame()

# Loop through each sample folder in the base directory
for sample_folder in os.listdir(base_path):
    sample_folder_path = os.path.join(base_path, sample_folder)

    # Check if it's a directory
    if os.path.isdir(sample_folder_path):
        print(f"Processing sample folder: {sample_folder}")

        # Find the MEGAHIT-sampleid.contigs_summary folder
        summary_folder = next((f for f in os.listdir(sample_folder_path) if f.startswith("MEGAHIT") and f.endswith(".contigs_summary")), None)
        if not summary_folder:
            print(f"No MEGAHIT summary folder found in {sample_folder}. Skipping...")
            continue

        summary_folder_path = os.path.join(sample_folder_path, summary_folder)

        # Dynamically find plasmid_summary.tsv and virus_summary.tsv
        for filename in os.listdir(summary_folder_path):
            file_path = os.path.join(summary_folder_path, filename)

            # Check for plasmid_summary.tsv
            if filename.endswith("plasmid_summary.tsv"):
                print(f"Found plasmid summary file in {sample_folder}: {filename}")
                try:
                    plasmid_df = pd.read_csv(file_path, sep='\t')
                    plasmid_df['Sample'] = sample_folder  # Add Sample column
                    plasmid_data = pd.concat([plasmid_data, plasmid_df], ignore_index=True)
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

            # Check for virus_summary.tsv
            elif filename.endswith("virus_summary.tsv"):
                print(f"Found virus summary file in {sample_folder}: {filename}")
                try:
                    virus_df = pd.read_csv(file_path, sep='\t')
                    virus_df['Sample'] = sample_folder  # Add Sample column
                    virus_data = pd.concat([virus_data, virus_df], ignore_index=True)
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

# Check if data was collected for plasmid and virus
if plasmid_data.empty:
    print("No plasmid data collected.")
else:
    # Save plasmid data to a CSV file
    plasmid_summary_path = os.path.join(base_path, "plasmid_contig_summary.csv")
    plasmid_data.to_csv(plasmid_summary_path, index=False)
    print(f"Plasmid summary data saved to {plasmid_summary_path}")

if virus_data.empty:
    print("No virus data collected.")
else:
    # Save virus data to a CSV file
    virus_summary_path = os.path.join(base_path, "virus_contig_summary.csv")
    virus_data.to_csv(virus_summary_path, index=False)
    print(f"Virus summary data saved to {virus_summary_path}")
